function d3header(f,width,height)

% fprintf(f,'<script>\n');
% fprintf(f,'var margin = {top: 20, right: 20, bottom: 30, left: 50},\n');
% fprintf(f,'    width = %d - margin.left - margin.right,\n',width);
% fprintf(f,'    height = %d - margin.top - margin.bottom;\n',height);
% fprintf(f,'var x = d3.scale.linear()\n');
% fprintf(f,'    .range([0, width]);\n');
% fprintf(f,'var y = d3.scale.linear()\n');
% fprintf(f,'    .range([height, 0]);\n');
% fprintf(f,'var xAxis = d3.svg.axis()\n');
% fprintf(f,'    .scale(x)\n');
% fprintf(f,'    .orient("bottom");\n');
% fprintf(f,'var yAxis = d3.svg.axis()\n');
% fprintf(f,'    .scale(y)\n');
% fprintf(f,'    .orient("left");\n');
% fprintf(f,'var svg = d3.select("body").append("svg")\n');
% fprintf(f,'    .attr("width", width + margin.left + margin.right)\n');
% fprintf(f,'    .attr("height", height + margin.top + margin.bottom)\n');
% fprintf(f,'    .append("g")\n');
% fprintf(f,'    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");\n');


fprintf(f,'var margin = {top: 20, right: 20, bottom: 30, left: 50},\n');
fprintf(f,'    width = %d - margin.left - margin.right,\n',width);
fprintf(f,'    height = %d - margin.top - margin.bottom;\n',height);
fprintf(f,'\n');
fprintf(f,'var svg = d3.select("body").append("svg")\n');
fprintf(f,'    .attr("width", width + margin.left + margin.right)\n');
fprintf(f,'    .attr("height", height + margin.top + margin.bottom)\n');
fprintf(f,'    .append("g")\n');
fprintf(f,'    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");\n');
fprintf(f,'\n');
fprintf(f,'var x = d3.scale.linear()\n');
fprintf(f,'    .range([0, width]);\n');
fprintf(f,'\n');
fprintf(f,'var y = d3.scale.linear()\n');
fprintf(f,'    .range([height, 0]);\n');
fprintf(f,'\n');
fprintf(f,'var create_xAxis = function() {\n');
fprintf(f,'    return d3.svg.axis()\n');
fprintf(f,'    .scale(x)\n');
fprintf(f,'    .orient("bottom"); }\n');
fprintf(f,'var create_yAxis = function() {\n');
fprintf(f,'    return d3.svg.axis()\n');
fprintf(f,'    .scale(y)\n');
fprintf(f,'    .orient("left"); }\n');
fprintf(f,'\n');
fprintf(f,'var yAxis = create_yAxis();\n');
fprintf(f,'\n');
fprintf(f,'svg.append("g")\n');
fprintf(f,'    .attr("class", "y axis")\n');
fprintf(f,'    .attr("transform", "(0,0)")\n');
fprintf(f,'    .call(yAxis);\n');
fprintf(f,'\n');
fprintf(f,'var xAxis = create_xAxis();\n');
fprintf(f,'\n');
fprintf(f,'svg.append("g")\n');
fprintf(f,'    .attr("class", "x axis")\n');
fprintf(f,'    .attr("transform", "translate(0," + height + ")")\n');
fprintf(f,'    .call(xAxis);\n');